-- Datos iniciales del catálogo (generado desde el catálogo original del sitio).
-- `published_at` es relativo a cuando se carga el seed: los publicados hace < 45 días se ven como "Nuevo".
-- Se carga con `npx supabase db reset`.

insert into public.categories (slug, label, image_url, sort_order, size_guide, complements) values
  ('camisetas', 'Camisetas', 'https://images.unsplash.com/photo-1526086754506-a57f69b4700a?auto=format&fit=crop&w=600&q=80', 1, 'apparel', array['shorts', 'zapatillas', 'accesorios']::text[]),
  ('shorts', 'Shorts', 'https://images.unsplash.com/photo-1688760117976-e3a339becff1?auto=format&fit=crop&w=600&q=80', 2, 'apparel', array['camisetas', 'accesorios', 'zapatillas']::text[]),
  ('zapatillas', 'Zapatillas', 'https://images.unsplash.com/photo-1631984564919-1f6b2313a71c?auto=format&fit=crop&w=600&q=80', 3, 'shoes', array['accesorios', 'shorts', 'camisetas']::text[]),
  ('buzos', 'Buzos', 'https://images.unsplash.com/photo-1652823780977-b22c0ed84c97?auto=format&fit=crop&w=600&q=80', 4, 'apparel', array['shorts', 'camperas', 'accesorios']::text[]),
  ('camperas', 'Camperas', 'https://images.unsplash.com/photo-1643622782660-30dedcd8d75a?auto=format&fit=crop&w=600&q=80', 5, 'apparel', array['buzos', 'camisetas', 'accesorios']::text[]),
  ('accesorios', 'Accesorios', 'https://images.unsplash.com/photo-1627627256672-027a4613d028?auto=format&fit=crop&w=600&q=80', 6, 'none', array['camisetas', 'shorts', 'zapatillas']::text[]);

insert into public.products
  (id, slug, name, description, category_slug, price, compare_at_price, images, sizes, colors, highlights, published_at, sort_order)
values
  ('r01', 'jersey-rebound-07', 'Jersey Rebound 07', 'Jersey de juego en mesh respirable con números sublimados. Sisa amplia para moverte sin límites y terminaciones en ribb.', 'camisetas', 42999, null, array['https://images.unsplash.com/photo-1526086754506-a57f69b4700a?auto=format&fit=crop&w=900&q=80']::text[], array['S', 'M', 'L', 'XL', 'XXL']::text[], '[{"name":"Morado","hex":"#8b3dff"},{"name":"Negro","hex":"#111111"}]'::jsonb, array['Mesh que respira y no se pega al cuerpo', 'Números sublimados: no se cuartean ni se despegan', 'Sisa amplia para tirar sin que te tire']::text[], now() - interval '3 days', 1),
  ('r02', 'camiseta-practice-reversible', 'Camiseta Practice Reversible', 'Camiseta reversible de entrenamiento: un lado claro, otro oscuro. Tela liviana de secado rápido, ideal para la práctica.', 'camisetas', 29999, 36999, array['https://images.unsplash.com/photo-1749743823062-df9d9de55e94?auto=format&fit=crop&w=900&q=80']::text[], array['S', 'M', 'L', 'XL', 'XXL']::text[], '[{"name":"Blanco","hex":"#f2f2f2"},{"name":"Negro","hex":"#111111"}]'::jsonb, array['Dos camisetas en una: clara y oscura', 'Seca rápido, ideal para entrenar', 'No se deforma con los lavados']::text[], now() - interval '60 days', 2),
  ('r03', 'jersey-street-league', 'Jersey Street League', 'Jersey de corte clásico para la liga del barrio. Mesh doble capa en hombros y laterales con paneles ventilados.', 'camisetas', 38999, null, array['https://images.unsplash.com/photo-1561781019-31d9dd448a61?auto=format&fit=crop&w=900&q=80']::text[], array['S', 'M', 'L', 'XL', 'XXL']::text[], '[{"name":"Naranja","hex":"#ff6a13"},{"name":"Negro","hex":"#111111"}]'::jsonb, array['Paneles ventilados en laterales', 'Doble capa en hombros: más resistente', 'Corte clásico que queda bien en la calle']::text[], now() - interval '75 days', 3),
  ('r04', 'musculosa-training-dry', 'Musculosa Training Dry', 'Musculosa de entrenamiento con tecnología de secado rápido. Calce atlético y costuras planas anti-roce.', 'camisetas', 21999, null, array['https://images.unsplash.com/photo-1666121363164-17a59d227812?auto=format&fit=crop&w=900&q=80']::text[], array['S', 'M', 'L', 'XL', 'XXL']::text[], '[{"name":"Verde oliva","hex":"#5b6b3a"},{"name":"Negro","hex":"#111111"}]'::jsonb, array['Secado rápido, no se empapa', 'Costuras planas: cero roce', 'Calce atlético, no ajustado']::text[], now() - interval '90 days', 4),
  ('r05', 'remera-oversize-court', 'Remera Oversize Court', 'Remera oversize de algodón pesado 24/1 para el post-partido. Cuello reforzado, caída amplia y hombros caídos.', 'camisetas', 24999, null, array['https://images.unsplash.com/photo-1726140872004-850c80900ae3?auto=format&fit=crop&w=900&q=80']::text[], array['S', 'M', 'L', 'XL', 'XXL']::text[], '[{"name":"Negro","hex":"#111111"},{"name":"Blanco","hex":"#f2f2f2"}]'::jsonb, array['Algodón pesado que no transparenta', 'No se achica ni se deforma al lavar', 'Caída oversize, estilo post-partido']::text[], now() - interval '8 days', 5),
  ('r06', 'short-mesh-pro', 'Short Mesh Pro', 'Short de mesh largo hasta la rodilla, cintura elástica con cordón y bolsillos laterales. El clásico de la cancha.', 'shorts', 27999, null, array['https://images.unsplash.com/photo-1688760117976-e3a339becff1?auto=format&fit=crop&w=900&q=80']::text[], array['S', 'M', 'L', 'XL', 'XXL']::text[], '[{"name":"Naranja","hex":"#ff6a13"},{"name":"Negro","hex":"#111111"},{"name":"Morado","hex":"#8b3dff"}]'::jsonb, array['Largo hasta la rodilla, como los de la cancha', 'Cintura elástica con cordón: no se baja', 'Bolsillos laterales profundos']::text[], now() - interval '12 days', 6),
  ('r07', 'short-swingman', 'Short Swingman', 'Short de juego con paneles laterales contrastantes y tela de punto liviana. Libertad total de movimiento.', 'shorts', 25999, 31999, array['https://images.unsplash.com/photo-1742473531981-12c925e98c19?auto=format&fit=crop&w=900&q=80']::text[], array['S', 'M', 'L', 'XL', 'XXL']::text[], '[{"name":"Negro","hex":"#111111"},{"name":"Blanco","hex":"#f2f2f2"}]'::jsonb, array['Tela liviana: libertad total de movimiento', 'Paneles laterales contrastantes', 'Cintura elástica cómoda todo el día']::text[], now() - interval '105 days', 7),
  ('r08', 'short-night-run', 'Short Night Run', 'Short liviano para jugar de noche o salir a correr. Calza interna y bolsillo trasero con cierre.', 'shorts', 23999, null, array['https://images.unsplash.com/photo-1763740355836-a26addadfbbd?auto=format&fit=crop&w=900&q=80']::text[], array['S', 'M', 'L', 'XL', 'XXL']::text[], '[{"name":"Rojo","hex":"#d62828"},{"name":"Negro","hex":"#111111"}]'::jsonb, array['Calza interna para jugar tranquilo', 'Bolsillo trasero con cierre para las llaves', 'Ultraliviano para jugar o correr']::text[], now() - interval '120 days', 8),
  ('r09', 'zapatillas-court-flight-mid', 'Zapatillas Court Flight Mid', 'Caña media con soporte de tobillo, amortiguación reactiva y suela de goma con patrón espiga para máximo agarre.', 'zapatillas', 149999, null, array['https://images.unsplash.com/photo-1631984564919-1f6b2313a71c?auto=format&fit=crop&w=900&q=80']::text[], array['39', '40', '41', '42', '43', '44', '45']::text[], '[{"name":"Negro","hex":"#111111"},{"name":"Naranja","hex":"#ff6a13"}]'::jsonb, array['Caña media que sostiene el tobillo', 'Suela espiga: agarre en cemento y parquet', 'Amortiguación reactiva en cada salto']::text[], now() - interval '18 days', 9),
  ('r10', 'zapatillas-fastbreak-low', 'Zapatillas Fastbreak Low', 'Caña baja liviana para jugadores rápidos. Capellada de cuero sintético y entresuela de espuma para la calle y la cancha.', 'zapatillas', 119999, 139999, array['https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1603808033176-9d134e6f2c74?auto=format&fit=crop&w=900&q=80']::text[], array['39', '40', '41', '42', '43', '44', '45']::text[], '[{"name":"Blanco","hex":"#f2f2f2"}]'::jsonb, array['Livianas para jugadores rápidos', 'Capellada fácil de limpiar', 'De la cancha a la calle sin cambiarte']::text[], now() - interval '135 days', 10),
  ('r11', 'zapatillas-blaze-runner', 'Zapatillas Blaze Runner', 'Running lifestyle con detalles en naranja, unidad de aire visible en el talón y malla transpirable.', 'zapatillas', 129999, null, array['https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=900&q=80']::text[], array['39', '40', '41', '42', '43', '44', '45']::text[], '[{"name":"Blanco","hex":"#f2f2f2"},{"name":"Naranja","hex":"#ff6a13"}]'::jsonb, array['Aire visible en el talón', 'Malla transpirable', 'Cómodas para usar todo el día']::text[], now() - interval '150 days', 11),
  ('r12', 'zapatillas-canvas-hi-top', 'Zapatillas Canvas Hi-Top', 'La bota de lona de siempre: caña alta, puntera de goma y suela vulcanizada. Un clásico del streetball.', 'zapatillas', 69999, null, array['https://images.unsplash.com/photo-1679736468688-a394f6a1646f?auto=format&fit=crop&w=900&q=80']::text[], array['39', '40', '41', '42', '43', '44', '45']::text[], '[{"name":"Negro","hex":"#111111"}]'::jsonb, array['Clásico del streetball que no pasa de moda', 'Puntera de goma resistente', 'Suela vulcanizada durable']::text[], now() - interval '165 days', 12),
  ('r13', 'hoodie-rebound-heavy', 'Hoodie Rebound Heavy', 'Buzo con capucha de frisa pesada 400 g, bolsillo canguro y puños acanalados. Para el calentamiento y la calle.', 'buzos', 54999, null, array['https://images.unsplash.com/photo-1652823780977-b22c0ed84c97?auto=format&fit=crop&w=900&q=80']::text[], array['S', 'M', 'L', 'XL', 'XXL']::text[], '[{"name":"Negro","hex":"#111111"},{"name":"Gris","hex":"#6b7280"}]'::jsonb, array['Frisa pesada 400 g: abriga de verdad', 'No hace bolitas con los lavados', 'Puños y cintura que no se estiran']::text[], now() - interval '25 days', 13),
  ('r14', 'hoodie-essential', 'Hoodie Essential', 'Buzo con capucha de frisa invisible, calce regular. El básico que combina con cualquier short o jogger.', 'buzos', 44999, 54999, array['https://images.unsplash.com/photo-1677538537484-324385aff147?auto=format&fit=crop&w=900&q=80']::text[], array['S', 'M', 'L', 'XL', 'XXL']::text[], '[{"name":"Gris","hex":"#6b7280"},{"name":"Negro","hex":"#111111"}]'::jsonb, array['El básico que combina con todo', 'Frisa suave por dentro', 'Calce regular, ni chico ni gigante']::text[], now() - interval '180 days', 14),
  ('r15', 'campera-warm-up', 'Campera Warm-Up', 'Campera de entrada en calor con franjas laterales, cierre completo y cuello alto. Estilo retro de banco de suplentes.', 'camperas', 74999, 89999, array['https://images.unsplash.com/photo-1643622782660-30dedcd8d75a?auto=format&fit=crop&w=900&q=80']::text[], array['S', 'M', 'L', 'XL', 'XXL']::text[], '[{"name":"Rojo","hex":"#d62828"},{"name":"Negro","hex":"#111111"}]'::jsonb, array['Estilo retro de banco de suplentes', 'Cuello alto que corta el viento', 'Cierre completo y bolsillos laterales']::text[], now() - interval '195 days', 15),
  ('r16', 'campera-shooting-windbreaker', 'Campera Shooting Windbreaker', 'Rompevientos liviano con paneles en bloque, capucha guardable y bolsillos con cierre. Repele el agua.', 'camperas', 69999, null, array['https://images.unsplash.com/photo-1611308725032-74f0a551d018?auto=format&fit=crop&w=900&q=80']::text[], array['S', 'M', 'L', 'XL', 'XXL']::text[], '[{"name":"Negro","hex":"#111111"},{"name":"Blanco","hex":"#f2f2f2"}]'::jsonb, array['Repele el agua', 'Capucha guardable en el cuello', 'Pesa casi nada: entra en la mochila']::text[], now() - interval '210 days', 16),
  ('r17', 'pelota-street-outdoor', 'Pelota Street Outdoor', 'Pelota de goma de alto agarre para canchas de cemento. Canales profundos y bote parejo. Tamaño oficial.', 'accesorios', 34999, null, array['https://images.unsplash.com/photo-1627627256672-027a4613d028?auto=format&fit=crop&w=900&q=80']::text[], array['Nº 7', 'Nº 6']::text[], '[{"name":"Naranja","hex":"#ff6a13"}]'::jsonb, array['Goma de alto agarre para cemento', 'Bote parejo y canales profundos', 'Tamaño oficial']::text[], now() - interval '225 days', 17),
  ('r18', 'medias-elite-crew', 'Medias Elite Crew x3', 'Pack de 3 pares de medias caña media con planta acolchada y zona de compresión en el arco.', 'accesorios', 12999, null, array['https://images.unsplash.com/photo-1589895869111-cab6bf8354c8?auto=format&fit=crop&w=900&q=80']::text[], array['39-42', '43-46']::text[], '[{"name":"Blanco","hex":"#f2f2f2"},{"name":"Negro","hex":"#111111"}]'::jsonb, array['Planta acolchada contra ampollas', 'Compresión en el arco', 'Pack de 3 pares']::text[], now() - interval '240 days', 18),
  ('r19', 'bolso-gym-duffle', 'Bolso Gym Duffle', 'Bolso deportivo con compartimento para zapatillas, correa regulable y tela resistente al agua.', 'accesorios', 39999, 47999, array['https://images.unsplash.com/photo-1708622833152-924c6e364138?auto=format&fit=crop&w=900&q=80']::text[], array['Único']::text[], '[{"name":"Negro","hex":"#111111"}]'::jsonb, array['Compartimento separado para zapatillas', 'Tela resistente al agua', 'Correa regulable y acolchada']::text[], now() - interval '255 days', 19);
-- Zonas de envío (precios de EJEMPLO: ajustalos en Studio → Table Editor → shipping_zones).
insert into public.shipping_zones (id, name, price, free_from, eta_label, sort_order) values
  ('caba', 'CABA', 3500, 120000, '24 a 48 h hábiles', 1),
  ('gba-1', 'GBA 1er cordón', 4500, 150000, '24 a 48 h hábiles', 2),
  ('gba-2', 'GBA 2do cordón', 5500, 180000, '48 a 72 h hábiles', 3),
  ('gba-3', 'GBA 3er cordón y La Plata', 7000, null, '48 a 72 h hábiles', 4),
  ('interior-pba', 'Interior de Buenos Aires', 9500, null, '3 a 5 días hábiles', 5);

-- CABA completa (todas sus comunas) e interior de la provincia como regla general.
insert into public.shipping_zone_areas (zone_id, provincia_id, departamento_id) values
  ('caba', '02', null),
  ('interior-pba', '06', null);

-- Partidos del conurbano (ids de departamento de Georef).
insert into public.shipping_zone_areas (zone_id, provincia_id, departamento_id)
select z.zone_id, '06', z.departamento_id
from (values
  -- 1er cordón: Avellaneda, Lanús, Lomas de Zamora, La Matanza, Morón, Tres de Febrero,
  -- Gral. San Martín, Vicente López, San Isidro, Hurlingham, Ituzaingó.
  ('gba-1', '06035'), ('gba-1', '06434'), ('gba-1', '06490'), ('gba-1', '06427'), ('gba-1', '06568'),
  ('gba-1', '06840'), ('gba-1', '06371'), ('gba-1', '06861'), ('gba-1', '06756'), ('gba-1', '06408'),
  ('gba-1', '06410'),
  -- 2do cordón: Quilmes, Berazategui, Florencio Varela, Almirante Brown, Esteban Echeverría, Ezeiza,
  -- Merlo, Moreno, José C. Paz, Malvinas Argentinas, San Miguel, San Fernando, Tigre.
  ('gba-2', '06658'), ('gba-2', '06091'), ('gba-2', '06274'), ('gba-2', '06028'), ('gba-2', '06260'),
  ('gba-2', '06270'), ('gba-2', '06539'), ('gba-2', '06560'), ('gba-2', '06412'), ('gba-2', '06515'),
  ('gba-2', '06760'), ('gba-2', '06749'), ('gba-2', '06805'),
  -- 3er cordón y Gran La Plata: Pilar, Escobar, Gral. Rodríguez, Marcos Paz, Presidente Perón,
  -- San Vicente, Cañuelas, La Plata, Berisso, Ensenada.
  ('gba-3', '06638'), ('gba-3', '06252'), ('gba-3', '06364'), ('gba-3', '06525'), ('gba-3', '06648'),
  ('gba-3', '06778'), ('gba-3', '06134'), ('gba-3', '06441'), ('gba-3', '06098'), ('gba-3', '06245')
) as z(zone_id, departamento_id);

-- Promoción vigente (EJEMPLO: editala o creá otra en Studio → promotions). Fechas en hora de Argentina.
insert into public.promotions (id, label, buy, pay, starts_at, ends_at) values
  ('octubre-3x2', '3x2', 3, 2, '2026-10-01 00:00:00-03', '2026-10-31 23:59:59-03');
